#define LITE 0
#if LITE
#define ARDUINO_OTA_ENABLED 0
#define FW_UPDATE_ENABLED 0
#define HA_ENABLED 0
#define DISPLAY_ENABLED 0
#define BME280_ENABLED 0
#define SHT2X_ENABLED 0
#define SHT3X_ENABLED 0
#define BH1750_ENABLED 0
#define BUZZER_ENABLED 0
#else
#define ARDUINO_OTA_ENABLED 0
#define FW_UPDATE_ENABLED 1
#define HA_ENABLED 1
#define DISPLAY_ENABLED 1
#define BME280_ENABLED 1
#define SHT2X_ENABLED 1
#define SHT3X_ENABLED 1
#define BH1750_ENABLED 1
#define BUZZER_ENABLED 1
#endif
