name: 'Upload Flasher to Github Pages'
description: 'Upload Flasher to Github Pages'
runs:
  using: 'composite'
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '${{ github.workspace }}/flasher'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
