name: 'Upload Flasher to Github Pages'
description: 'Upload Flasher to Github Pages'
inputs:
  binary_path:
    description: 'Path to the binary'
    default: ''
  beta_binary_path:
    description: 'Path to the beta binary'
    default: ''
  beta_s3_binary_path:
    description: 'Path to the beta s3 binary'
    default: ''
  beta_c3_binary_path:
    description: 'Path to the beta c3 binary'
    default: ''
  lite_binary_path:
    description: 'Path to the lite binary'
    default: ''
  version:
    description: 'Version of the binary'
    default: ''
  beta_build:
    description: 'Beta build number'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Copy bin to flasher
      if: ${{ inputs.binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.binary_path }} ${{ github.workspace }}/flasher/bins/jaam.bin
    - name: Copy beta bin to flasher
      if: ${{ inputs.beta_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.beta_binary_path }} ${{ github.workspace }}/flasher/bins/jaam_beta.bin
    - name: Copy beta s3 bin to flasher
      if: ${{ inputs.beta_s3_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.beta_s3_binary_path }} ${{ github.workspace }}/flasher/bins/jaam_beta_s3.bin
    - name: Copy beta c3 bin to flasher
      if: ${{ inputs.beta_c3_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.beta_c3_binary_path }} ${{ github.workspace }}/flasher/bins/jaam_beta_c3.bin
    - name: Copy lite bin to flasher
      if: ${{ inputs.lite_binary_path != '' }}
      shell: bash
      run: |
        cp -f ${{ inputs.lite_binary_path }} ${{ github.workspace }}/flasher/bins/jaam_lite.bin
    - name: Change version in flasher
      if: ${{ inputs.binary_path != '' }}
      shell: bash
      run: |
        sed -E -i "s/(Встановити JAAM )[0-9.]+/\1${{ inputs.version }}/" ${{ github.workspace }}/flasher/index.html
        sed -E -i "s/(Отримати опис JAAM )[0-9.]+/\1${{ inputs.version }}/" ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}",/' ${{ github.workspace }}/flasher/manifest.json
        sed -E -i "s/(fetchReleaseNotes\(')[0-9.]+('\))/\1${{ inputs.version }}\2/" ${{ github.workspace }}/flasher/index.html
    - name: Change beta version in flasher
      if: ${{ inputs.beta_binary_path != '' }}
      shell: bash
      run: |
        sed -E -i "s/(Встановити JAAM )[0-9.]+( Beta )[0-9]+/\1${{ inputs.version }}\2${{ inputs.beta_build }}/" ${{ github.workspace }}/flasher/index.html
        sed -E -i "s/(Отримати опис JAAM )[0-9.]+ Beta [0-9]+/\1${{ inputs.version }} Beta ${{ inputs.beta_build }}/" ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}-b${{ inputs.beta_build }}",/' ${{ github.workspace }}/flasher/manifest-beta.json
        sed -E -i "s/(fetchReleaseNotes\(')[0-9.]+-b[0-9]+('\))/\1${{ inputs.version }}-b${{ inputs.beta_build }}\2/" ${{ github.workspace }}/flasher/index.html
    - name: Change lite version in flasher
      if: ${{ inputs.lite_binary_path != '' }}
      shell: bash
      run: |
        sed -E -i "s/(Встановити JAAM )[0-9.]+( Lite)/\1${{ inputs.version }}\2/" ${{ github.workspace }}/flasher/index.html
        sed -i 's/"version": ".*",/"version": "${{ inputs.version }}",/' ${{ github.workspace }}/flasher/manifest-lite.json
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '${{ github.workspace }}/flasher'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
