name: 🧪 Deploy Dev Server
on:
  workflow_dispatch:
    inputs:
      server_choice:
        type: choice
        default: 'Server 1'
        description: Choose server
        options:
          - 'Server 1'
          - 'Server 2'
      redeploy_updater_dev:
        type: boolean
        default: false
        description: Updater Dev
      redeploy_websocket_dev:
        type: boolean
        default: false
        description: Websocket Dev
      weather_source:
        type: choice
        description: "Weather data source"
        required: true
        default: "openmeteo"
        options:
          - openmeteo
          - openweathermap
      google_stat:
        type: boolean
        description: "Enable Google stat"
        default: true
      ping_interval:
        type: number
        description: "Websocket ping interval (in seconds)"
        default: 60
      ping_timeout:
        type: number
        description: "Websocket ping timeout (in seconds)"
        default: 30
      ping_timeout_count:
        type: number
        description: "Websocket ping timeout count before disconnect"
        default: 1
      logging:
        type: choice
        description: "Log level"
        required: true
        default: "DEBUG"
        options:
          - DEBUG
          - INFO
          - WARNING
          - CRITICAL
          - ERROR

permissions:
  contents: read

run-name: Deploy Dev Websockets from '${{ github.ref_name }}' branch
jobs:
    pytests:
      uses: ./.github/workflows/pytests.yml
    deploy_websocket_dev:
        needs: pytests
        runs-on: ubuntu-latest
        env:
          SERVER_IP: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_IP || secrets.CLOUD_SERVER_2_IP }}
          SERVER_USER: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_USER || secrets.CLOUD_SERVER_2_USER }}
          SERVER_SSH_KEY: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_SSH_KEY || secrets.CLOUD_SERVER_2_SSH_KEY }}
        steps:
          - name: Redeploy Updater Dev
            if: ${{ inputs.redeploy_updater_dev }}
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                TEMP_DIR=$(mktemp -d)
                cd $TEMP_DIR
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
                cd deploy/
                bash redeploy_updater_dev.sh \
                  -l ${{ inputs.logging }} \
                  -m ${{ secrets.CLOUD_REDIS_HOST }} \
                  -pw ${{ secrets.CLOUD_REDIS_PASSWORD }}
                cd /
                rm -rf $TEMP_DIR
          - name: Redeploy WebSockets Dev
            if: ${{ inputs.redeploy_websocket_dev }}
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                TEMP_DIR=$(mktemp -d)
                cd $TEMP_DIR
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
                cd deploy/
                bash redeploy_websocket_server_dev.sh \
                  -m ${{ secrets.CLOUD_REDIS_HOST }} \
                  -pw ${{ secrets.CLOUD_REDIS_PASSWORD }} \
                  -s ${{ secrets.API_SECRET }} \
                  -i ${{ secrets.MEASUREMENT_ID }} \
                  -g ${{ inputs.google_stat && 'True' || 'False' }} \
                  -l ${{ inputs.logging }} \
                  -p ${{ inputs.ping_interval }} \
                  -t ${{ inputs.ping_timeout }} \
                  -c ${{ inputs.ping_timeout_count }} \
                  -k ${{ secrets.IP_INFO_TOKEN }} \
                  -w ${{ inputs.weather_source }}
                cd /
                rm -rf $TEMP_DIR
          - name: Clear unused images
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                docker image prune -f
