name: 🗄️ Deploy Redis
on:
  workflow_dispatch:
    inputs:
      server_choice:
        type: choice
        default: 'Server 1'
        description: Choose server
        options:
          - 'Server 1'
          - 'Server 2'

run-name: Deploy Redis from '${{ github.ref_name }}' branch
permissions:
  contents: read
jobs:
    deploy_redis:
        runs-on: ubuntu-latest
        env:
          SERVER_IP: "${{ inputs.server_choice == 'Server 1' ? secrets.CLOUD_SERVER_IP : secrets.CLOUD_SERVER_2_IP }}"
          SERVER_USER: "${{ inputs.server_choice == 'Server 1' ? secrets.CLOUD_SERVER_USER : secrets.CLOUD_SERVER_2_USER }}"
          SERVER_SSH_KEY: "${{ inputs.server_choice == 'Server 1' ? secrets.CLOUD_SERVER_SSH_KEY : secrets.CLOUD_SERVER_2_SSH_KEY }}"
        steps:
          - name: Redeploy Redis
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                set -euo pipefail
                TEMP_DIR=$(mktemp -d)
                trap 'rm -rf "$TEMP_DIR"' EXIT
                cd "$TEMP_DIR"
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
                cd deploy/
                bash redeploy_redis.sh \
                  -w ${{ secrets.CLOUD_REDIS_PASSWORD }}
          - name: Clear unused images
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                docker image prune -f
