name: ⚖️ Deploy Bot Guard
on: 
  workflow_dispatch:
    inputs:
      server_choice:
        type: choice
        default: 'Сервер 1'
        description: Вибір сервера
        options:
          - 'Сервер 1'
          - 'Сервер 2'
      use_captcha:
        type: boolean
        default: true
        description: Капча замість питань
      logging:
        type: choice
        description: "Log level"
        required: true
        default: "INFO"
        options:
          - DEBUG
          - INFO
          - WARNING
          - CRITICAL
          - ERROR
permissions:
  contents: read
jobs:
    deploy_bot_guard:
        runs-on: ubuntu-latest
        env:
          SERVER_IP: ${{ inputs.server_choice == 'Сервер 1' && secrets.CLOUD_SERVER_IP || secrets.CLOUD_SERVER_2_IP }}
          SERVER_USER: ${{ inputs.server_choice == 'Сервер 1' && secrets.CLOUD_SERVER_USER || secrets.CLOUD_SERVER_2_USER }}
          SERVER_SSH_KEY: ${{ inputs.server_choice == 'Сервер 1' && secrets.CLOUD_SERVER_SSH_KEY || secrets.CLOUD_SERVER_2_SSH_KEY }}
        steps:
          - name: Redeploy Bot Guard
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                TEMP_DIR=$(mktemp -d)
                cd $TEMP_DIR
                git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
                cd deploy/
                bash redeploy_bot_guard.sh \
                  -a ${{ secrets.BOT_GUARD_ALLOWED_CHAT_IDS }} \
                  -b ${{ secrets.BOT_GUARD_TOKEN }} \
                  -c ${{ inputs.use_captcha }} \
                  -l ${{ inputs.logging }}
                cd /
                rm -rf $TEMP_DIR
          - name: Clear unused images
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ env.SERVER_IP }}
              username: ${{ env.SERVER_USER }}
              key: ${{ env.SERVER_SSH_KEY }}
              script: |
                docker image prune -f
