name: 🔄 Deploy Update Server
permissions: {}
on:
  workflow_dispatch:
    
run-name: Deploy Updater from '${{ github.ref_name }}' branch
jobs:
    pytests:
      uses: ./.github/workflows/pytests.yml
    deploy_updater:
        needs: pytests
        runs-on: ubuntu-latest
        steps:
          - name: Redeploy Updater
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ secrets.CLOUD_SERVER_IP }}
              username: ${{ secrets.CLOUD_SERVER_USER }}
              key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}
              script: |
                cd /root/ukraine_alarm_map/deploy/
                git fetch --all
                git switch ${{ github.ref_name }}
                git pull
                bash redeploy_updater.sh \
                  -m ${{ secrets.CLOUD_REDIS_HOST }} \
                  -pw ${{ secrets.CLOUD_REDIS_PASSWORD }}
          - name: Clear unused images
            uses: appleboy/ssh-action@v1.2.0
            with:
              host: ${{ secrets.CLOUD_SERVER_IP }}
              username: ${{ secrets.CLOUD_SERVER_USER }}
              key: ${{ secrets.CLOUD_SERVER_SSH_KEY }}
              script: |
                docker image prune -f
