name: 🧹 Lint Check
on:
  push:
    branches:
      - develop
    paths:
      - "flasher/**"
      - "deploy/**"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - develop
    paths:
      - "flasher/**"
      - "deploy/**"
jobs:
  check_flasher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check flasher with proof-html
        uses: anishathalye/proof-html@v2
        with:
            directory: ${{ github.workspace }}/flasher
  run_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black in the check mode
        uses: psf/black@stable
        with:
          options: "--check --verbose --line-length 120 --diff --color --target-version py312"
          src: ${{ github.workspace }}/deploy
          version: "~= 24.0"
  run_pytest:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'
      - name: Install dependencies from deploy subfolders
        run: |
          cd deploy
          for req_file in $(find . -name "requirements.txt"); do
            echo "Installing dependencies from $req_file"
            pip install -r "$req_file"
          done
      - name: Add deploy to PYTHONPATH
        run: |
          DEPLOY_PATH=$(pwd)/deploy
          if [ -z "$PYTHONPATH" ]; then
            echo "PYTHONPATH=$DEPLOY_PATH" >> $GITHUB_ENV
          else
            echo "PYTHONPATH=${PYTHONPATH}:$DEPLOY_PATH" >> $GITHUB_ENV
          fi
      - name: Debug PYTHONPATH
        run: |
          echo "Current PYTHONPATH: $PYTHONPATH"
      - name: Run PyTest in deploy/tests
        run: |
          cd deploy/tests
          pip install pytest  # Ensure pytest is installed
          pytest --tb=short -v --capture=tee-sys