name: 🔄 Setup Logrotate
on:
  workflow_dispatch:
    inputs:
      server_choice:
        type: choice
        default: 'Server 1'
        description: Choose server
        options:
          - 'Server 1'
          - 'Server 2'

run-name: Setup logrotate on server from '${{ github.ref_name }}' branch
permissions:
  contents: read
jobs:
  setup_logrotate:
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_IP || secrets.CLOUD_SERVER_2_IP }}
      SERVER_USER: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_USER || secrets.CLOUD_SERVER_2_USER }}
      SERVER_SSH_KEY: ${{ inputs.server_choice == 'Server 1' && secrets.CLOUD_SERVER_SSH_KEY || secrets.CLOUD_SERVER_2_SSH_KEY }}
    steps:
      - name: Install logrotate configs
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          script: |
            TEMP_DIR=$(mktemp -d)
            cd $TEMP_DIR
            git clone --branch ${{ github.ref_name }} https://github.com/${{ github.repository }}.git .
            cd deploy/
            bash setup_logrotate.sh \
              -l ${{ secrets.CLOUD_NGINX_LOGS }}
            cd /
            rm -rf $TEMP_DIR
